//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreBuildInternshipProblem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreBuildInternshipProblem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;characters&gt;
        ///  &lt;character&gt;
        ///    &lt;attack&gt;10&lt;/attack&gt;
        ///    &lt;description&gt;Make America great again&lt;/description&gt;
        ///    &lt;health&gt;100&lt;/health&gt;
        ///    &lt;id&gt;1&lt;/id&gt;
        ///    &lt;isVillain&gt;false&lt;/isVillain&gt;
        ///    &lt;name&gt;Captain America&lt;/name&gt;
        ///  &lt;/character&gt;
        ///  &lt;character&gt;
        ///    &lt;attack&gt;100&lt;/attack&gt;
        ///    &lt;description&gt;The Most Powerful Being in the Universe&lt;/description&gt;
        ///    &lt;health&gt;300&lt;/health&gt;
        ///    &lt;id&gt;2&lt;/id&gt;
        ///    &lt;isVillain&gt;true&lt;/isVillain&gt;
        ///    &lt;name&gt;Thanos&lt;/name&gt;
        ///  &lt;/character&gt;
        ///  &lt;ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string characters {
            get {
                return ResourceManager.GetString("characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon1 {
            get {
                object obj = ResourceManager.GetObject("icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;planets&gt;
        ///  &lt;planet&gt;
        ///    &lt;description&gt;Earth-616, Home of the Avengers, also you.&lt;/description&gt;
        ///    &lt;id&gt;1&lt;/id&gt;
        ///    &lt;modifiers&gt;
        ///      &lt;heroAttackModifier&gt;10&lt;/heroAttackModifier&gt;
        ///      &lt;heroHealthModifier&gt;30&lt;/heroHealthModifier&gt;
        ///      &lt;villainAttackModifier&gt;-20&lt;/villainAttackModifier&gt;
        ///      &lt;villainHealthModifier&gt;-10&lt;/villainHealthModifier&gt;
        ///    &lt;/modifiers&gt;
        ///    &lt;name&gt;Earth&lt;/name&gt;
        ///  &lt;/planet&gt;
        ///  &lt;planet&gt;
        ///    &lt;description&gt;One of the Nine Worlds and home to the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string planets {
            get {
                return ResourceManager.GetString("planets", resourceCulture);
            }
        }
    }
}
